CREATE MATERIALIZED VIEW echantillon_propriete AS (
    SELECT *
    FROM crosstab(
            $$
            SELECT CAST (id AS INTEGER),
                propriete,
                COALESCE(valeur, cast (valeur_num as varchar))
            FROM liste_propriete $$,
                $$
            SELECT DISTINCT lp.propriete
            FROM liste_propriete lp
            ORDER BY lp.propriete $$
        ) AS res (
            id int4,
            _3_4_methylenedioxyethylamphetamine decimal,
            _3_4_methylene_dioxy_methylamphetamine decimal,
            _3_4_methylenedioxyphenylacetone decimal,
            _4F_MDMB_BUTINACA decimal,
            _5F_ADB decimal,
            _5F_MDMB_PICA decimal,
            Abime varchar(255),
            Acetylcodeine decimal,
            Acetylthebaol decimal,
            Acide_4_hydroxybutanoique decimal,
            Acide_benzoique decimal,
            Acide_borique decimal,
            ADB_BUTINACA decimal,
            Amidon decimal,
            Aminopyrine decimal,
            Amoxycilline decimal,
            Amphetamine decimal,
            Benzocaine decimal,
            Benzoylecgonine decimal,
            Bicarbonate_de_sodium decimal,
            Bicarbonates decimal,
            Buprenorphine decimal,
            Cafeine decimal,
            Cannabidiol decimal,
            Cannabigerol decimal,
            Cannabinol decimal,
            CBD varchar(255),
            CBN varchar(255),
            Cis_cinnamoylcocaine decimal,
            Clonazepam decimal,
            Clotrimazole decimal,
            Cocaine decimal,
            Codeine decimal,
            Couleur varchar(255),
            Couleur_exterieur varchar(255),
            Couleur_exterieur_1 varchar(255),
            Couleur_exterieur_2 varchar(255),
            Couleur_interieur varchar(255),
            Creatine decimal,
            Delta8_Tetrahydrocannabinol decimal,
            Delta9_Tetrahydrocannabinol decimal,
            Description_de_l_Objet varchar(255),
            Dextromethorphane decimal,
            Diametre decimal,
            Diltiazem decimal,
            Dimethylterephtalate decimal,
            Diphenydramine decimal,
            Ecgonidine decimal,
            Ecgoninemethylester decimal,
            Epaisseur decimal,
            Etiquette varchar(255),
            Forme varchar(255),
            FUB_AMB decimal,
            Gammabutyrolactone decimal,
            Glucose decimal,
            Griseofulvine decimal,
            Guaifenesine decimal,
            Hauteur decimal,
            Heroine decimal,
            Hydroxyzine decimal,
            Ibuprofene decimal,
            Inositol decimal,
            isoleucine decimal,
            Ketamine decimal,
            Lactitol decimal,
            Lactose decimal,
            Largeur decimal,
            Leucine decimal,
            Levamisole decimal,
            Lidocaine decimal,
            Logo varchar(255),
            Longueur decimal,
            Maltose decimal,
            Mannitol decimal,
            Masse decimal,
            MDMB_4en_PINACA decimal,
            Meconine decimal,
            Methamphetamine decimal,
            Methylecgonidine decimal,
            Monoacetylmorphine decimal,
            Morphine decimal,
            Nicotine decimal,
            N_methyl_tryptamine decimal,
            Nom_de_logo varchar(255),
            Norcocaine decimal,
            Noscapine decimal,
            Numero_echantillon varchar(255),
            O3_Monoacetylmorphine_ decimal,
            O6_Monoacetylmorphine decimal,
            Ovule varchar(255),
            Oxycodone decimal,
            Papaverine decimal,
            Paracetamol decimal,
            Phenacetine decimal,
            Piracetam decimal,
            Presentation varchar(255),
            Procaine decimal,
            PV8 decimal,
            Saccharose decimal,
            Secabilite_recto varchar(255),
            Secabilite_verso varchar(255),
            Sorbitol decimal,
            Talc decimal,
            Taux_cbd decimal,
            Taux_cbn decimal,
            Terephtalates decimal,
            Tetracaine decimal,
            Tramadol decimal,
            Trans_cinnamoylcocaine decimal,
            Tropacocaine decimal,
            Type_drogue varchar(255),
            Uree decimal,
            Valine decimal,
            Vanilline decimal,
            Visqueux varchar(255)
        )
);